{% set commit = "97fd5253d69b76a15f0b306e19fe89beda4bc5d7" %}
{% set version = "0.3.0" %}

package:
  name: symengine
  version: {{ version }}

source:
  fn: {{ commit }}.tar.gz
  url: https://github.com/symengine/symengine/archive/{{ commit }}.tar.gz
  patches:
    # https://github.com/symengine/symengine/pull/1260
    - 1260.patch

build:
  number: 3
  msvc_compiler: 14.0
  features:
    - vc14             # [win]

requirements:
  build:
    - toolchain        # [unix]
    - cmake
    - gmp >=5.0.1,<7   # [unix]
    - mpir 3.*         # [win]
    - mpfr 3.*
    - mpc 1.*
    - vc 14            # [win]
    - llvmdev 3.9.*    # [not win32]
  run:
    - gmp >=5.0.1,<7   # [unix]
    - mpir 3.*         # [win]
    - mpfr 3.*
    - mpc 1.*
    - vc 14            # [win]

test:
  commands:
    - if not exist %LIBRARY_INC%\\symengine\\basic.h exit 1     # [win]
    - if not exist %LIBRARY_LIB%\\symengine.lib exit 1          # [win]
    - if not exist %LIBRARY_BIN%\\symengine.dll exit 1          # [win]
    - test -f $PREFIX/include/symengine/basic.h                 # [unix]
    - test -f $PREFIX/lib/libsymengine.so                       # [linux]
    - test -f $PREFIX/lib/libsymengine.dylib                    # [osx]

about:
  home: https://github.com/symengine/symengine
  license: MIT
  license_file: LICENSE
  summary: 'SymEngine is a fast symbolic manipulation library, written in C++'

extra:
  recipe-maintainers:
    - isuruf
    - certik
